### ISSUE TITLE
`chrome.storage`

### ISSUE THREAD

**Issue by cobaltt7** [otiai10/chrome-extension-es6-import#1]
Thanks for this! But I have a problem. In the imported script, I can't access the `chrome.storage` api. `chrome.runtime` yes, but not `chrome.storage`. Is there any hack that would allow me to do so?

Thanks in advance!

**Comment by otiai10** [comment]
Check the official document here https://developer.chrome.com/docs/extensions/reference/storage/ and find you need to add "storage" permission in your manifest

**Comment by cobaltt7** [comment]
No, it's added. I think it is because by the time the exported class imports the exported function which uses a function from another exported class it's no longer considered part of the extension. I ended up using messages instead.
________________________________
